# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# Create User for Testing
user1 = User.create!(email: "test1@test.com", password: "123456")


# Create tags
tag1 = Tag.create!(name: "Asian")
tag2 = Tag.create!(name: "Mexican")
tag3 = Tag.create!(name: "British")
# tag5 = Tag.create!(name: "Breakfast")
# tag6 = Tag.create!(name: "Lunch")
# tag7 = Tag.create!(name: "Dinner")
# tag8 = Tag.create!(name: "Snack")/

# Create recipes
recipe1 = Recipe.create!(name: "Brekky Dumplings", description: "", instructions: "", prep_time: 30, cook_time: 120, user_id: 1, meal_type: ["Breakfast"])
recipe2 = Recipe.create!(name: "Lunch Tacos", description: "", instructions: "", prep_time: 30, cook_time: 120, user_id: 1, meal_type: ["Lunch"])
recipe3 = Recipe.create!(name: "Steak and ale pie", description: "", instructions: "", prep_time: 30, cook_time: 120, user_id: 1, meal_type: ["Dinner"])
recipe4 = Recipe.create!(name: "Brekky Noodles", description: "", instructions: "", prep_time: 30, cook_time: 120, user_id: 1, meal_type: ["Breakfast"])
recipe5 = Recipe.create!(name: "Lunch Fajitas", description: "", instructions: "", prep_time: 30, cook_time: 120, user_id: 1, meal_type: ["Lunch"])
recipe6 = Recipe.create!(name: "Fish and chips", description: "", instructions: "", prep_time: 30, cook_time: 120, user_id: 1, meal_type: ["Dinner"])

# Associate tags with recipes through the join table
recipe1.tags << tag1
recipe2.tags << tag2
recipe3.tags << tag3
recipe4.tags << tag1
recipe5.tags << tag2
recipe6.tags << tag3



puts "Recipes and tags created"

meats = [
  "Sirloin",
  "Ribeye",
  "Tenderloin (filet mignon)",
  "Flank steak",
  "Chuck roast",
  "Brisket",
  "Short ribs",
  "Ground beef (minced beef)",
  "Pork chops",
  "Pork tenderloin",
  "Pork belly",
  "Spare ribs",
  "Pork shoulder (Boston butt)",
  "Ham",
  "Bacon",
  "Ground pork",
  "Lamb chops",
  "Leg of lamb",
  "Lamb shoulder",
  "Lamb shank",
  "Ground lamb",
  "Veal chops",
  "Veal tenderloin",
  "Veal cutlets",
  "Ground veal",
  "Chicken breast",
  "Chicken thighs",
  "Chicken drumsticks",
  "Whole chicken",
  "Duck breast",
  "Duck legs",
  "Turkey breast",
  "Turkey legs",
  "Ground chicken",
  "Ground turkey",
  "Venison (deer)",
  "Rabbit",
  "Pheasant",
  "Quail",
  "Wild boar",
  "Bison",
  "Elk",
  "Ostrich",
  "Liver",
  "Kidneys",
  "Hearts",
  "Tongue",
  "Sweetbreads",
  "Tripe",
  "Brains",
  "Pork sausages",
  "Chicken Sausages",
  "Hot dogs",
  "Ham",
  "Turkey",
  "Salami",
  "Pepperoni",
  "Bacon",
  "Corned beef",
  "Pastrami",
  "Spam",
  "Jerky"
]

meats.each do |meat|
  Ingredient.create!(name: "#{meat}", description: "meat")
end

seafood = [
  "Salmon",
  "Tuna",
  "Cod",
  "Mahi Mahi",
  "Halibut",
  "Trout",
  "Snapper",
  "Mackerel",
  "Swordfish",
  "Haddock",
  "Tilapia",
  "Catfish",
  "Grouper",
  "Bass",
  "Perch",
  "Sole",
  "Flounder",
  "Sardines",
  "Anchovies",
  "Carp",
  "Pike",
  "Eel",
  "Wahoo",
  "Lobster",
  "Crab",
  "Shrimp (prawns)",
  "Crawfish (crayfish)",
  "Clams",
  "Mussels",
  "Oysters",
  "Scallops",
  "Abalone",
  "Conch",
  "Octopus",
  "Squid (calamari)",
  "Cuttlefish",
  "Cockles",
  "Razor clams",
  "Geoduck",
  "Caviar (roe)",
  "Seaweed (nori, wakame, kombu, dulse, etc.)",
  "Sea snails (whelks, periwinkles)"
]

seafood.each do |item|
  Ingredient.create!(name: "#{item}", description: "seafood")
end

dairyandeggs = [
  "Cow's milk",
  "Goat's milk",
  "Sheep's milk",
  "Unsalted butter",
  "Salted butter",
  "Plain yogurt",
  "Flavored yogurt",
  "Greek yogurt",
  "Regular yogurt",
  "Cheddar cheese",
  "Mozzarella cheese",
  "Swiss cheese",
  "Feta cheese",
  "Parmesan cheese",
  "Brie cheese",
  "Blue cheese",
  "Goat cheese",
  "Heavy cream",
  "Whipping cream",
  "Sour cream",
  "Cottage Cheese",
  "Ricotta Cheese",
  "Mascarpone Cheese",
  "Cream Cheese",
  "Buttermilk",
  "Evaporated Milk",
  "Condensed Milk",
  "Ice Cream",
  "Gelato",
  "Sherbet",
  "Frozen Yogurt",
  "Kefir",
  "Labneh",
  "Whey",
  "Ghee (Clarified Butter)",
  "Quark",
  "Fromage Blanc",
  "Crème Fraîche",
  "Chicken eggs",
  "Duck eggs",
  "Quail eggs",
  "Egg whites",
  "Egg yolks",
  "Liquid egg whites (carton)",
  "Liquid egg yolks (carton)",
  "Egg beaters",
  "Powdered egg whites",
  "Powdered egg yolks"
]

dairyandeggs.each do |item|
  Ingredient.create!(name: "#{item}", description: "dairy and eggs")
end

vegetables = [
  "Russet potatoes",
  "Yukon Gold potatoes",
  "Red potatoes",
  "Fingerling potatoes",
  "Purple potatoes",
  "Sweet potatoes",
  "New potatoes",
  "White onions",
  "Red onions",
  "Yellow onions",
  "Shallots",
  "Green onions (Scallions)",
  "Leeks",
  "Garlic",
  "Beefsteak tomatoes",
  "Roma tomatoes",
  "Cherry tomatoes",
  "Grape tomatoes",
  "Heirloom tomatoes",
  "Plum tomatoes",
  "Orange carrots",
  "Purple carrots",
  "Yellow carrots",
  "White carrots",
  "Green bell peppers",
  "Red bell peppers",
  "Yellow bell peppers",
  "Orange bell peppers",
  "Iceberg lettuce",
  "Romaine lettuce",
  "Butterhead lettuce",
  "Arugula (Rocket)",
  "Red leaf lettuce",
  "Green leaf lettuce",
  "Boston lettuce",
  "Baby spinach",
  "Savoy spinach",
  "Broccoli",
  "Broccolini",
  "Broccoli rabe (Rapini)",
  "White cauliflower",
  "Purple cauliflower",
  "Romanesco cauliflower",
  "Green cabbage",
  "Red cabbage",
  "Savoy cabbage",
  "Napa cabbage (Chinese cabbage)",
  "Aubergine",
  "Globe eggplant",
  "Japanese eggplant",
  "Italian eggplant",
  "Zucchini (Courgette)",
  "Button mushrooms",
  "Cremini mushrooms",
  "Portobello mushrooms",
  "Shiitake mushrooms",
  "Oyster mushrooms",
  "Chanterelle mushrooms",
  "Enoki mushrooms",
  "Morel mushrooms",
  "Porcini mushrooms",
  "Green Beans (String Beans)",
  "Green peas",
  "Snow peas",
  "Snap peas",
  "Corn (Maize):",
  "Sweet corn",
  "Baby corn",
  "Red radishes",
  "Daikon radishes",
  "Celery",
  "English cucumbers",
  "Persian cucumbers",
  "Avocado",
  "Sugar pumpkins",
  "Pie pumpkins",
  "Kabocha squash",
  "Butternut squash",
  "Acorn squash",
  "Spaghetti squash",
  "Zucchini",
  "Asparagus",
  "Kale:",
  "Curly kale",
  "Lacinato kale (Dinosaur kale)",
]

vegetables.each do |item|
  Ingredient.create!(name: "#{item}", description: "vegetable")
end

fruits = [
  "Granny Smith apples",
  "Red Delicious apples",
  "Gala apples",
  "Fuji apples",
  "Honeycrisp apples",
  "Pink Lady apples",
  "Golden Delicious apples",
  "Braeburn apples",
  "McIntosh apples",
  "Cavendish bananas",
  "Plantains",
  "Red bananas",
  "Lady Finger bananas",
  "Navel oranges",
  "Valencia oranges",
  "Blood oranges",
  "Mandarin oranges",
  "Clementines",
  "Satsumas",
  "Tangerines",
  "Seville oranges",
  "Red grapes",
  "Green grapes",
  "Black grapes",
  "Thompson seedless grapes",
  "Concord grapes",
  "Muscat grapes",
  "Strawberries",
  "Blueberries",
  "Raspberries",
  "Blackberries",
  "Cranberries",
  "Goji berries",
  "Acai berries",
  "Boysenberries",
  "Lemons",
  "Limes",
  "Grapefruits",
  "Pomelos",
  "Kumquats",
  "Yuzu",
  "Peaches",
  "Nectarines",
  "Plums",
  "Apricots",
  "Cherries",
  "Mangoes",
  "Pineapples",
  "Papayas",
  "Kiwifruits",
  "Passion fruits",
  "Guavas",
  "Lychees",
  "Dragon fruits",
  "Jackfruits",
  "Star fruits",
  "Watermelons",
  "Cantaloupes (Muskmelons)",
  "Honeydews",
  "Galia melons",
  "Crenshaw melons",
  "Granny Smith apples",
  "Red Delicious apples",
  "Gala apples",
  "Fuji apples",
  "Honeycrisp apples",
  "Pink Lady apples",
  "Golden Delicious apples",
  "Braeburn apples",
  "McIntosh apples",
  "Bartlett pears",
  "Bosc pears",
  "Anjou pears",
  "Asian pears",
  "Forelle pears",
  "Comice pears",
  "Bing cherries",
  "Rainier cherries",
  "Sweet cherries",
  "Sour cherries",
  "Red plums",
  "Black plums",
  "Green plums",
  "Hawaiian papayas",
  "Mexican papayas",
  "Caribbean papayas",
  "Black figs",
  "Brown figs",
  "Green figs",
  "Fuyu persimmons",
  "Hachiya persimmons",
  "Fresh cranberries",
  "Dried cranberries",
  "Green kiwifruits",
  "Gold kiwifruits",
  "Medjool dates",
  "Deglet Noor dates",
  "Red pomegranates",
  "White pomegranates",
  "Ataulfo mangoes",
  "Tommy Atkins mangoes",
  "Champagne mangoes",
  "Pink guavas",
  "White guavas",
  "Red lychees",
  "Yellow lychees",
  "Red dragon fruits",
  "White dragon fruits",
  "Purple passion fruits",
]

fruits.each do |item|
  Ingredient.create!(name: "#{item}", description: "fruit")
end

grainsandcereals = [
  "Wheat berries",
  "Wheat flour",
  "Whole wheat bread",
  "Bulgur",
  "Farro",
  "Semolina",
  "Durum wheat",
  "White rice",
  "Brown rice",
  "Jasmine rice",
  "Basmati rice",
  "Arborio rice",
  "Sushi rice",
  "Black rice",
  "Wild rice",
  "Cornmeal",
  "Polenta",
  "Grits",
  "Corn flour",
  "Corn flakes",
  "Pearl barley",
  "Hulled barley",
  "Barley flour",
  "Rolled oats",
  "Steel-cut oats",
  "Instant oats",
  "Oat flour",
  "Rye berries",
  "Rye flour",
  "Pumpernickel bread",
  "Pearl millet",
  "Finger millet (Ragi)",
  "Foxtail millet",
  "Proso millet",
  "White quinoa",
  "Red quinoa",
  "Black quinoa",
  "Buckwheat groats",
  "Buckwheat flour",
  "Soba noodles",
  "Sorghum flour",
  "Sorghum syrup",
  "Teff flour",
  "Injera (Ethiopian flatbread)",
  "Fonio grains",
  "Amaranth grains",
  "Amaranth flour",
  "Spelt flour",
  "Spelt bread",
  "Kamut flour",
  "Kamut pasta",
  "Bulgur",
  "Farro",
  "Freekeh",
  "Triticale",
  "Emmer",
  "Einkorn",
  "Chia Seeds",
  "Hemp Seeds",
  "Sunflower Seeds",
  "Flax Seeds"
]

grainsandcereals.each do |item|
  Ingredient.create!(name: "#{item}", description: "grains and cereal")
end

legumesandpulses = [
  "Brown lentils",
  "Green lentils",
  "Red lentils",
  "French lentils (Puy lentils)",
  "Black lentils (Beluga lentils)",
  "Canned chickpeas",
  "Dried chickpeas",
  "Canned black beans",
  "Dried black beans",
  "Canned kidney beans",
  "Dried kidney beans",
  "Canned navy beans",
  "Dried navy beans",
  "Canned pinto beans",
  "Dried pinto beans",
  "Canned cannellini beans",
  "Dried cannellini beans",
  "Dried adzuki beans",
  "Dried mung beans",
  "Mung bean sprouts",
  "Canned black-eyed peas",
  "Dried black-eyed peas",
  "Green split peas",
  "Yellow split peas",
  "Dried fava beans",
  "Edamame",
  "Tofu",
  "Tempeh",
  "Soy milk",
  "Soy flour",
  "Dried cowpeas",
  "Dried lima beans",
  "Green peas",
  "Split peas",
  "Dried lupini beans",
  "Chickpea Flour (Gram Flour/Besan)",
  "Whole urad dal",
  "Split urad dal (Black lentils)",
  "Whole moong dal",
  "Split moong dal",
  "Whole masoor dal",
  "Split masoor dal",
  "Split chana dal",
  "Split toor dal",
  "Whole green lentils",
  "Whole red lentils",
]

legumesandpulses.each do |item|
  Ingredient.create!(name: "#{item}", description: "legumes and pulses")
end

nutsandseeds = [
  "Raw almonds",
  "Almond butter",
  "Almond flour",
  "Raw walnuts",
  "Walnut halves",
  "Raw cashews",
  "Cashew butter",
  "Raw pistachios",
  "Pistachio kernels",
  "Raw pecans",
  "Pecan halves",
  "Raw hazelnuts",
  "Hazelnut butter",
  "Raw macadamia nuts",
  "Raw Brazil nuts",
  "Raw pine nuts",
  "Raw peanuts",
  "Peanut butter",
  "Raw sunflower seeds",
  "Sunflower seed butter",
  "Raw pumpkin seeds",
  "Raw sesame seeds",
  "Tahini (sesame seed paste)",
  "Whole flax seeds",
  "Ground flax seeds (flaxseed meal)",
  "Hulled hemp seeds (hemp hearts)",
  "Hemp seed oil",
  "Raw poppy seeds",
  "Quinoa seeds",
  "Amaranth seeds",
  "Buckwheat groats",
  "Buckwheat flour",
  "Millet seeds",
  "Fresh pomegranate seeds",
  "Shredded coconut",
  "Coconut flakes",
  "Coconut flour",
  "Coconut oil",
  "Raw cashews",
  "Cashew butter",
  "Raw chestnuts",
]

nutsandseeds.each do |item|
  Ingredient.create!(name: "#{item}", description: "nuts and seeds")
end

herbsandspices = [
  "Basil",
  "Parsley",
  "Cilantro (Coriander)",
  "Mint",
  "Thyme",
  "Rosemary",
  "Sage",
  "Oregano",
  "Dill",
  "Chives",
  "Bay Leaves",
  "Tarragon",
  "Marjoram",
  "Lavender",
  "Lemongrass",
  "Curry Leaves",
  "Cumin Seeds",
  "Coriander Seeds",
  "Fennel Seeds",
  "Mustard Seeds",
  "Fenugreek Seeds",
  "Caraway Seeds",
  "Celery Seeds",
  "Nigella Seeds (Black Cumin)",
  "Cardamom Pods",
  "Cloves",
  "Cinnamon Sticks",
  "Nutmeg",
  "Allspice",
  "Star Anise",
  "Saffron",
  "Turmeric",
  "Ginger",
  "Garlic Powder",
  "Onion Powder",
  "Chili Powder",
  "Paprika",
  "Cayenne Pepper",
  "Red Pepper Flakes",
  "Black Pepper",
  "White Pepper",
  "Ground Cumin",
  "Ground Coriander",
  "Ground Ginger",
  "Ground Turmeric",
  "Ground Cinnamon",
  "Ground Cloves",
  "Ground Nutmeg",
  "Ground Allspice",
  "Ground Cardamom",
  "Ground Fenugreek",
  "Curry Powder",
  "Garam Masala",
  "Chinese Five Spice",
  "Za'atar",
  "Herbes de Provence",
  "Italian Seasoning",
  "Ras el Hanout",
  "Cajun Seasoning",
  "Old Bay Seasoning",
  "Adobo Seasoning",
  "Jerk Seasoning",
  "Poultry Seasoning",
  "Taco Seasoning",
  "Fajita Seasoning",
  "Berbere Spice",
  "Dukkah",
  "Harissa",
  "Sumac",
  "Asafoetida (Hing)",
  "Epazote",
  "Kaffir Lime Leaves",
  "Lemongrass",
  "Mace",
  "Vanilla Bean",
]

herbsandspices.each do |item|
  Ingredient.create!(name: "#{item}", description: "herbs and spices")
end

oilsandfats = [
  "Extra virgin olive oil",
  "Virgin olive oil",
  "Pure olive oil",
  "Light olive oil",
  "Virgin coconut oil",
  "Refined coconut oil",
  "Fractionated coconut oil",
  "Canola Oil (Rapeseed Oil)",
  "Soybean oil",
  "Corn oil",
  "Sunflower oil",
  "Safflower oil",
  "Cottonseed oil",
  "Avocado Oil",
  "Peanut Oil (Groundnut Oil)",
  "Toasted sesame oil",
  "Unrefined sesame oil",
  "Flaxseed Oil (Linseed Oil)",
  "Walnut Oil",
  "Grapeseed Oil",
  "Almond Oil",
  "Hazelnut Oil (Filbert Oil)",
  "Macadamia Nut Oil",
  "Pistachio Oil",
  "Rice Bran Oil",
  "Sunflower Oil",
  "Safflower Oil",
  "Unsalted butter",
  "Salted butter",
  "Ghee (Clarified Butter)",
  "Lard",
  "Duck Fat",
  "Goose Fat",
  "Schmaltz (Rendered Chicken Fat)",
  "Tallow (Beef Fat)",
  "Shortening",
  "Margarine",
  "Cocoa Butter",
  "Palm Oil",
  "Fish Oil",
  "Emu Oil",
  "Hemp Seed Oil",
  "Camelina Oil",
  "Pumpkin Seed Oil",
  "Apricot Kernel Oil",
  "Rice Bran Oil",
  "Tamanu Oil",
  "Black Seed Oil",
  "Argan Oil",
  "Jojoba Oil",
  "Meadowfoam Oil",
  "Marula Oil",
  "Baobab Oil",
  "Neem Oil",
  "Tea Tree Oil",
  "Castor Oil",
  "Rosehip Oil",
  "Evening Primrose Oil",
  "Borage Oil",
  "Sea Buckthorn Oil",
  "Wheat Germ Oil",
]

oilsandfats.each do |item|
  Ingredient.create!(name: "#{item}", description: "oils and fats")
end

sweeteners = [
  "White Sugar (Granulated Sugar)",
  "Brown Sugar",
  "Confectioners' Sugar (Powdered Sugar)",
  "Cane Sugar",
  "Turbinado Sugar",
  "Demerara Sugar",
  "Muscovado Sugar",
  "Coconut Sugar",
  "Date Sugar",
  "Maple Syrup",
  "Honey",
  "Agave Syrup",
  "Molasses",
  "Rice Syrup (Brown Rice Syrup)",
  "Corn Syrup",
  "High-Fructose Corn Syrup",
  "Stevia",
  "Monk Fruit Sweetener",
  "Xylitol",
  "Erythritol",
  "Sorbitol",
  "Maltitol",
  "Allulose",
  "Invert Sugar",
  "Barley Malt Syrup",
]

sweeteners.each do |item|
  Ingredient.create!(name: "#{item}", description: "sweeteners")
end

condimentsandsauces = [
  "Ketchup",
  "Yellow mustard",
  "Dijon mustard",
  "Whole grain mustard",
  "Mayonnaise",
  "BBQ Sauce",
  "Tabasco",
  "Sriracha",
  "Soy Sauce",
  "Worcestershire Sauce",
  "Fish Sauce",
  "Hoisin Sauce",
  "Oyster Sauce",
  "Teriyaki Sauce",
  "Sweet Chili Sauce",
  "Tartar Sauce",
  "Ranch Dressing",
  "Blue Cheese Dressing",
  "Caesar Dressing",
  "Italian Dressing",
  "Balsamic Vinaigrette",
  "Thousand Island Dressing",
  "Salsa",
  "Guacamole",
  "Hummus",
  "Pesto",
  "Tahini",
  "Harissa",
  "Chimichurri Sauce",
  "Hollandaise Sauce",
  "Bechamel Sauce",
  "Marinara Sauce",
  "Alfredo Sauce",
  "Pesto Sauce",
  "Sriracha Mayo",
  "Cocktail Sauce",
  "Soy Ginger Glaze",
  "Sweet and Sour Sauce",
  "Gochujang",
  "Peanut Sauce",
  "Miso Paste",
  "Tzatziki Sauce",
  "Chipotle Mayo",
  "Enchilada Sauce",
  "Szechuan Sauce",
  "Ponzu Sauce",
  "Black Bean Sauce",
  "Thai Curry Paste",
  "Mole Sauce",
  "Pickles",
  "Relish",
  "Chutney",
  "Aioli",
]

condimentsandsauces.each do |item|
  Ingredient.create!(name: "#{item}", description: "condiments and sauces")
end

bakingandcookingessentials = [
  "All-Purpose Flour",
  "Granulated Sugar",
  "Brown Sugar",
  "Baking Powder",
  "Baking Soda",
  "Salt (Table Salt, Kosher Salt, Sea Salt)",
  "Vanilla Extract",
  "Yeast",
  "Cornstarch",
  "Cocoa Powder",
  "Chocolate Chips",
  "Vegetable Oil",
  "Olive Oil",
  "Butter",
  "Eggs",
  "Milk",
  "Cream (Heavy Cream, Whipping Cream)",
  "Sour Cream",
  "Yogurt",
  "Honey",
  "Molasses",
  "Maple Syrup",
  "Cornmeal",
  "Bread Crumbs",
  "Panko Bread Crumbs",
  "Canned Tomatoes",
  "Crushed Tomatoes (can)",
  "Diced Tomatoes (can)",
  "Tomato Paste (can)",
  "Chicken Broth",
  "Beef Broth",
  "Vegetable Broth",
  "White Vinegar",
  "Apple Cider Vinegar",
  "Balsamic Vinegar",
  "Soy Sauce",
  "Worcestershire Sauce",
  "Dijon Mustard",
  "Canned Black Beans",
  "Canned Kidney Beans",
  "Canned Chickpeas",
  "Canned Coconut Milk",
  "Canned Pumpkin Puree",
  "Canned Condensed Milk",
  "Gelatin",
  "Shortening",
  "Confectioners' Sugar",
  "Almond Extract",
  "Lemon Extract",
  "Cream of Tartar",
  "White Wine",
  "Red Wine",
  "Rice Vinegar",
  "Mirin",
  "Cooking Wine",
  "Coconut Oil",
  "Agar Agar",
]

bakingandcookingessentials.each do |item|
  Ingredient.create!(name: "#{item}", description: "baking and cooking essentials")
end

beverages = [
  "Coffee",
  "Tea",
  "Water",
  "Milk",
  "Almond Milk",
  "Soy Milk",
  "Oat Milk",
  "Coconut Milk",
  "Rice Milk",
  "Orange Juice",
  "Apple Juice",
  "Grape Juice",
  "Cranberry Juice",
  "Carbonated Water",
  "Lemonade",
  "Hot Chocolate",
  "Ginger Tea",
  "Chai Tea",
  "Matcha Tea",
  "Kombucha",
  "Red Wine",
  "White Wine",
  "Rosé Wine",
  "Lager",
  "Ale",
  "Stout",
  "Vodka",
  "Rum",
  "Whiskey",
  "Gin",
  "Tequila",
  "Champagne",
  "Sparkling Wine",
  "Sake",
  "Cider",
  "Coconut Water",
  "Tonic Water",
  "Cola",
  "Lemon-Lime Soda",
  "Ginger Ale",
  "Coconut Water",
  "Fruit Infused Water",
  "Peppermint Infusion",
  "Chamomile Infusion",
  "Yerba Mate",
  "Espresso",
  "Americano",
  "Cappuccino",
  "Latte",
  "Macchiato",
  "Flat White",
  "Irish Coffee",
  "Turkish Coffee",
]

beverages.each do |item|
  Ingredient.create!(name: "#{item}", description: "beverage")
end

pasta = [
  "Spaghetti",
  "Linguine",
  "Fettuccine",
  "Tagliatelle",
  "Penne",
  "Rigatoni",
  "Fusilli",
  "Rotini",
  "Farfalle (Bowtie)",
  "Conchiglie (Shell)",
  "Orecchiette",
  "Ravioli",
  "Tortellini",
  "Gnocchi",
  "Orzo",
  "Cavatappi",
  "Manicotti",
  "Cannelloni",
  "Gemelli",
  "Campanelle",
  "Pappardelle",
  "Capellini (Angel Hair)",
  "Ziti",
  "Rotelle",
  "Paccheri",
  "Paccheri",
  "Strozzapreti",
  "Mafaldine",
  "Gigli",
  "Farfalloni",
]

pasta.each do |item|
  Ingredient.create!(name: "#{item}", description: "pasta")
end

miscellaneous = [
  "Truffle Oil",
  "Vanilla Beans",
  "Saffron Threads",
  "Edible Gold Leaf",
  "Lavender Extract",
  "Rose Water",
  "Orange Blossom Water",
  "Almond Extract",
  "Peppermint Extract",
  "Coconut Extract",
  "Maple Extract",
  "Food Coloring (Liquid, Gel)",
  "Agar Agar Powder",
  "Xanthan Gum",
  "Guar Gum",
  "Arrowroot Powder",
  "Cornstarch",
  "Cream of Tartar",
  "Instant Coffee",
  "Baking Spray (Non-stick spray)",
  "Pectin",
  "Malt Extract",
  "Yeast",
  "Balsamic Vinegar",
  "Rice Vinegar",
  "Apple Cider Vinegar",
  "Mirin",
  "Miso Paste",
  "Tahini Paste",
  "Fish Sauce",
  "Worcestershire Sauce",
  "Gochujang",
  "Hoisin Sauce",
  "Harissa Paste",
  "Wasabi Paste",
  "Mirin",
  "Rice Wine",
  "Rice Vinegar",
  "Seaweed Sheets (Nori)",
  "Tamarind Paste",
  "Furikake",
  "Rice Paper",
  "Coconut Aminos",
  "Dashi Powder",
  "Thai Curry Paste",
  "Lemon Grass",
  "Galangal",
  "Kaffir Lime Leaves",
  "Rice Noodles",
  "Udon Noodles",
  "Soba Noodles",
  "Coconut Cream",
]

miscellaneous.each do |item|
  Ingredient.create!(name: "#{item}", description: "miscellaneous")
end
recipe1.ingredients << Ingredient.where(name: "Chicken breast").first
recipe2.ingredients << Ingredient.where(name: "Ribeye").first
recipe3.ingredients << Ingredient.where(name: "Sirloin").first
recipe4.ingredients << Ingredient.where(name: "Pork belly").first
recipe5.ingredients << Ingredient.where(name: "Chicken thighs").first
recipe6.ingredients << Ingredient.where(name: "Cod").first
